<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${countryName} — ${siteName}</title>
</head>
<body>
  <nav><a href="../index.html">&larr; Home</a></nav>

  <h1>${countryName}</h1>

  <h2>Leagues</h2>
  <ul>
  <#list leagues as league>
    <li><a href="${league.slug}/index.html">${league.name}</a> — Season ${league.season}</li>
  </#list>
  </ul>

  <footer>
    <p>Generated by <a href="https://github.com/omer3kale/MCFootball">MCFootball</a></p>
  </footer>
</body>
</html>
