<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${siteName} — Home</title>
</head>
<body>
  <h1>${siteName}</h1>
  <p>Football results site generated by MCFootball.</p>

  <h2>Countries</h2>
  <ul>
  <#list countries as country>
    <li>
      <a href="${country.slug}/index.html">${country.name}</a>
      <ul>
      <#list country.leagues as league>
        <li><a href="${country.slug}/${league.slug}/index.html">${league.name} (${league.season})</a></li>
      </#list>
      </ul>
    </li>
  </#list>
  </ul>

  <footer>
    <p>Generated by <a href="https://github.com/omer3kale/MCFootball">MCFootball</a></p>
  </footer>
</body>
</html>
