<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${leagueName} — ${countryName} — ${siteName}</title>
</head>
<body>
  <nav>
    <a href="../../index.html">Home</a> &gt;
    <a href="../index.html">${countryName}</a> &gt;
    ${leagueName}
  </nav>

  <h1>${leagueName}</h1>
  <h2>Season ${season}</h2>

<#if (matches?size > 0)>
  <table border="1" cellpadding="6" cellspacing="0">
    <thead>
      <tr>
        <th>Date</th>
        <th>Time</th>
        <th>Home</th>
        <th>Away</th>
        <th>Score</th>
        <th>Stadium</th>
      </tr>
    </thead>
    <tbody>
    <#list matches as m>
      <tr>
        <td>${m.date}</td>
        <td>${m.time}</td>
        <td>${m.homeTeam} (${m.homeCity})</td>
        <td>${m.awayTeam} (${m.awayCity})</td>
        <td>${m.homeScore} – ${m.awayScore}</td>
        <td>${m.stadium}</td>
      </tr>
    </#list>
    </tbody>
  </table>
<#else>
  <p>No matches recorded yet.</p>
</#if>

  <footer>
    <p>Generated by <a href="https://github.com/omer3kale/MCFootball">MCFootball</a></p>
  </footer>
</body>
</html>
